sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.070.0
 - dmd-2.069.2
 - dmd-2.068.2
 - ldc-0.17.0-beta2
 - ldc-0.16.1
 - gdc-4.9.2
 - gdc-5.2.0

matrix:
  allow_failures:
   - d: ldc-0.15.1
     env: TEST=runtests:test_extra
   - d: ldc-0.16.1
     env: TEST=runtests:test_extra

   - d: gdc-4.9.2
   - d: gdc-5.2.0
   - os: osx
     d: gdc-4.9.2
   - os: osx
     d: gdc-5.2.0

env:
 - ARCH=x86
 - ARCH=x86_64

env:
 - TEST_PYTHON=python2
 - TEST_PYTHON=python3

addons:
  apt:
    packages:
     - python3
     - python
     - python3-numpy
     - python-numpy
     - python-dev
     - python3-dev

install:
 - if [ $TRAVIS_OS_NAME == osx ];
   then
     brew update;
     brew install python python3;
     brew install homebrew/python/numpy --with-python3;
   fi

script:
  - cd examples && ./runAll.sh $TEST_PYTHON $DC $ARCH
