sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd
 - ldc
 - gdc

matrix:
  allow_failures:
   - d: gdc

env:
 - ARCH=x86
 - ARCH=x86_64

env:
 - TEST_PYTHON=python2
 - TEST_PYTHON=python3

addons:
  apt:
    packages:
     - python3
     - python
     - python3-numpy
     - python-numpy
     - python-dev
     - python3-dev

install:
 - if [ $TRAVIS_OS_NAME == osx ];
   then
     brew update;
     brew install python python3;
     brew install homebrew/python/numpy --with-python3;
   fi

script:
 - cd examples && ./runAll.sh $TEST_PYTHON $DC $ARCH
